server:
  port: 5725

spring:
  redis:
    host: localhost
    port: 6379
    database: 1
  servlet:
    multipart:
      max-request-size: 2048MB
      max-file-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kchat?rewriteBatchedStatements=true
    username: root
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis-plus:
  mapperLocations: classpath:Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: Logs/app.log  # 日志文件名和路径
  level:
    root: INFO  # 根日志级别
    org.springframework.web: DEBUG  # 特定包的日志级别
    com.baomidou.mybatisplus: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 文件日志格式

jwt:
  secretKey: MineCraft&LOL&Naruto@game12306
  audience: Audience
  issuer: Issuer

email:
  host: 2504319659@qq.com
  authorizationCode: oigluerlhjqcebcj

resource:
  img:
    pattern: /img/**
    path: D:/repos/KChatResource/imgs
    location: file:D:/repos/KChatResource/imgs/
  file:
    pattern: /file/**
    path: D:/repos/KChatResource/files
    location: file:D:/repos/KChatResource/files/

netty:
  path: /ws
  port: 5726
  maxContentLength: 65536
  handshakeTimeOut: 100000

